/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import backup.PostgresBackup;
import backup.PostgresRestore;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Elivelton Silva
 */
public class Backup extends javax.swing.JInternalFrame {

    /**
     * Creates new form Backup
     */
    public Backup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGeraBackup = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        btnRestauraBackup = new javax.swing.JToggleButton();

        setClosable(true);
        setTitle("Backup e Restauração");

        btnGeraBackup.setText("Gerar Backup do Sistema");
        btnGeraBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeraBackupActionPerformed(evt);
            }
        });

        jLabel1.setText("O backup será salvo em C:\\Sistema Rodrigo\\backup\\backup_sistema.backup");

        btnRestauraBackup.setText("Restaurar Backup no Sistema");
        btnRestauraBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestauraBackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnGeraBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRestauraBackup, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGeraBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnRestauraBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        setBounds(0, 0, 497, 308);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeraBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeraBackupActionPerformed
        PostgresBackup postgresBackup = new PostgresBackup();
        try {
            postgresBackup.realizaBackup();
        } catch (IOException ex) {
            Logger.getLogger(Backup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Backup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGeraBackupActionPerformed

    private void btnRestauraBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestauraBackupActionPerformed
        PostgresRestore postgresRestore = new PostgresRestore();
        postgresRestore.restauraBackup();
    }//GEN-LAST:event_btnRestauraBackupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnGeraBackup;
    private javax.swing.JToggleButton btnRestauraBackup;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
