/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ServicosDAO;
import factory.ConnectionFactory;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Clientes;
import model.Servicos;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author elivelton
 */
public class CadServicos extends javax.swing.JInternalFrame {

    VlistaClientes vlistaClientes = new VlistaClientes();

    Clientes clientes;
    Servicos servicos;
    ServicosDAO sdao;

    //método recebo o código do JFrame vlistaClientes
    public void executaOutraTela(String codigo, String nome) {
        txtCodigoCliente.setText(codigo);
        txtNomeCliente.setText(nome);
    }

    //limpa todos os campos
    public void Clear() {
        txtDescricao.setText("");
        txtCodigoCliente.setText("");
        txtNomeCliente.setText("");
        txtNumero.setText("");
        txtValor.setText("");
        txtPesqNome.setText("");
        txtData.setText("");

        //carrega tabela de serviços
        this.listaServicos("");
    }

    //Carrega Serviços cadastrados
    public void listaServicos(String nome) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("NÚMERO");
        modelo.addColumn("COD. CLIENTE");
        modelo.addColumn("CLIENTE");
        modelo.addColumn("SERVIÇO");
        modelo.addColumn("VALOR");
        modelo.addColumn("DATA");

        sdao = new ServicosDAO();

        for (Servicos s : sdao.listLimit(nome)) {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            String dataFormatada = formato.format(s.getData());

            modelo.addRow(new Object[]{s.getCodigo(), s.getNumero(), s.getClientes().getCodigo(),
                s.getClientes().getNome(), s.getDescricao(), Double.toString(s.getValor()).replace(".", ","), dataFormatada});
        }

        tbServicos.setModel(modelo);
    }
    
    //Carrega Serviços cadastrados
    public void listaAllServicos(String nome) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("NÚMERO");
        modelo.addColumn("COD. CLIENTE");
        modelo.addColumn("CLIENTE");
        modelo.addColumn("SERVIÇO");
        modelo.addColumn("VALOR");
        modelo.addColumn("DATA");

        sdao = new ServicosDAO();

        for (Servicos s : sdao.listAll(nome)) {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            String dataFormatada = formato.format(s.getData());

            modelo.addRow(new Object[]{s.getCodigo(), s.getNumero(), s.getClientes().getCodigo(),
                s.getClientes().getNome(), s.getDescricao(), Double.toString(s.getValor()).replace(".", ","), dataFormatada});
        }

        tbServicos.setModel(modelo);
    }

    //desabilita campos
    public void desabilitaCampos() {
        txtData.disable();
        txtDescricao.disable();
        txtNomeCliente.disable();
        txtNumero.disable();
        txtValor.disable();
        btnSelecionar.setVisible(false);
    }

    //habilita campos
    public void habilitaCampos() {
        txtData.enable();
        txtDescricao.enable();
        txtNomeCliente.enable();
        txtNumero.enable();
        txtValor.enable();
        btnSelecionar.setVisible(true);
    }

    /**
     * Creates new form CadServicos
     */
    public CadServicos() {
        initComponents();

        this.listaServicos("");
        lbcodigo.setVisible(false);

        //botões invisiveis
        btnSalvar.setVisible(false);
        btnExcluir.setVisible(false);
        btnEditar.setVisible(false);

        desabilitaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnSelecionar = new javax.swing.JButton();
        txtNomeCliente = new javax.swing.JTextField();
        txtData = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtValor = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JEditorPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbServicos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtPesqNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        lbcodigo = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadastro de Serviços");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel3.setText("Valor:");

        jLabel4.setText("Cliente:");

        txtCodigoCliente.setEditable(false);

        jLabel5.setText("Data:");

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Número:");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Exlcuir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFocusLost(evt);
            }
        });

        jLabel2.setText("Descrição:");

        jScrollPane1.setViewportView(txtDescricao);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Serviços"));

        tbServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbServicos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbServicosFocusLost(evt);
            }
        });
        tbServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbServicosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbServicos);

        jLabel7.setText("Pesquisar por nome:");

        txtPesqNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqNomeKeyReleased(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
        );

        lbcodigo.setText("codigo_servico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lbcodigo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbcodigo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        vlistaClientes.MostraTela(this);
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void tbServicosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbServicosMousePressed
        habilitaCampos();
        
        btnSalvar.setVisible(false);
        btnEditar.setVisible(true);
        btnExcluir.setVisible(true);
        lbcodigo.setText(tbServicos.getModel().getValueAt(tbServicos.getSelectedRow(), 0) + "");
        txtNumero.setText(tbServicos.getModel().getValueAt(tbServicos.getSelectedRow(), 1) + "");
        txtCodigoCliente.setText(tbServicos.getModel().getValueAt(tbServicos.getSelectedRow(), 2) + "");
        txtNomeCliente.setText(tbServicos.getModel().getValueAt(tbServicos.getSelectedRow(), 3) + "");
        txtDescricao.setText(tbServicos.getModel().getValueAt(tbServicos.getSelectedRow(), 4) + "");
        txtValor.setText(tbServicos.getModel().getValueAt(tbServicos.getSelectedRow(), 5) + "");
        txtData.setText(tbServicos.getModel().getValueAt(tbServicos.getSelectedRow(), 6) + "");
    }//GEN-LAST:event_tbServicosMousePressed

    private void txtPesqNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqNomeKeyReleased

    }//GEN-LAST:event_txtPesqNomeKeyReleased

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        //this.listaServicos(txtPesqNome.getText().toUpperCase());
        listaAllServicos(txtPesqNome.getText().toUpperCase());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        habilitaCampos();
        
        this.Clear();
        this.listaServicos("");
        btnSalvar.setVisible(true);
        btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
        txtData.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        try {
            servicos = new Servicos();
            clientes = new Clientes();
            sdao = new ServicosDAO();

            //formata data para salvar no banco
            String dia = txtData.getText().substring(0, 2);
            String mes = txtData.getText().substring(3, 5);
            String ano = txtData.getText().substring(6);

            String dataSalva = ano + "-" + mes + "-" + dia;

            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-ddd");
            Date data = formato.parse(dataSalva);

            clientes.setCodigo(Integer.parseInt(txtCodigoCliente.getText()));

            servicos.setDescricao(txtDescricao.getText().toUpperCase());
            servicos.setNumero(Integer.parseInt(txtNumero.getText()));
            servicos.setValor(Double.parseDouble(txtValor.getText().replace(",", ".")));
            servicos.setClientes(clientes);
            servicos.setData(data);
            sdao.salvar(servicos);

            this.listaServicos("");
            
            this.Clear();
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            
            desabilitaCampos();

            //Imprime recibo
            Connection con = ConnectionFactory.conectar();

            String caminho = "C:/relatorios/comprovante.jasper";
            //String caminho = "C:/Users/Elivelton Silva/Documents/NetBeansProjects/Rodrigo_Foto/src/relatorio_temp/comprovante.jasper";
            try {
                JasperPrint print = JasperFillManager.fillReport(caminho, null, con);

                JasperViewer jv = new JasperViewer(print, false);
                jv.setVisible(true); //chama o formulario para visualização
                jv.toFront(); //set o formulario a frente da aplicação
                btnSalvar.setVisible(false);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao chamar o relatório!\nErro:" + ex);
                ex.printStackTrace();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Valor inválido para Número ou Valor!/Preencha todos os campos!", "Atenção", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Informe a Data do Serviço!", "Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            servicos = new Servicos();
            clientes = new Clientes();
            sdao = new ServicosDAO();

            //formata data para salvar no banco
            String dia = txtData.getText().substring(0, 2);
            String mes = txtData.getText().substring(3, 5);
            String ano = txtData.getText().substring(6);

            String dataSalva = ano + "-" + mes + "-" + dia;

            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-ddd");
            Date data = formato.parse(dataSalva);

            clientes.setCodigo(Integer.parseInt(txtCodigoCliente.getText()));

            servicos.setCodigo(Integer.parseInt(lbcodigo.getText()));
            servicos.setDescricao(txtDescricao.getText().toUpperCase());
            servicos.setNumero(Integer.parseInt(txtNumero.getText()));
            servicos.setValor(Double.parseDouble(txtValor.getText().replace(",", ".")));
            servicos.setClientes(clientes);
            servicos.setData(data);

            sdao.editar(servicos);

            this.listaServicos("");
            this.Clear();
            JOptionPane.showMessageDialog(null, "Editado com sucesso!");
            btnEditar.setVisible(false);
            btnSalvar.setVisible(false);
            btnExcluir.setVisible(false);
            
            desabilitaCampos();

            //System.out.println(servicos.getData());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Valor inválido para Número ou Valor!/Preencha todos os campos!", "Atenção", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Informe a Data do Serviço!", "Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        servicos = new Servicos();
        sdao = new ServicosDAO();

        servicos.setCodigo(Integer.parseInt(lbcodigo.getText()));

        sdao.excluir(servicos);

        this.listaServicos("");
        btnExcluir.setVisible(false);
        btnEditar.setVisible(false);
        btnSalvar.setVisible(false);
        this.Clear();
        
        desabilitaCampos();
        
        JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusLost

    }//GEN-LAST:event_txtValorFocusLost

    private void tbServicosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbServicosFocusLost

    }//GEN-LAST:event_tbServicosFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbcodigo;
    private javax.swing.JTable tbServicos;
    public javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JEditorPane txtDescricao;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesqNome;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
