/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ServicosDAO;
import factory.ConnectionFactory;
import java.sql.Connection;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Servicos;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author elivelton
 */
public class ConsultaServico extends javax.swing.JInternalFrame {

    Servicos servicos;
    ServicosDAO sdao;

    //Carrega tabela consulta de serviços
    public void listaServicos() throws ParseException {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("NUMERO");
        modelo.addColumn("CPF");
        modelo.addColumn("NOME");
        modelo.addColumn("SERVIÇO");
        modelo.addColumn("VALOR");
        modelo.addColumn("DATA");

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date data_inicial = formato.parse(txtDataInicial.getText());
        Date data_final = formato.parse(txtDataFinal.getText());

        sdao = new ServicosDAO();

        for (Servicos s : sdao.consultaEntreDatas(data_inicial, data_final)) {

            Double valor = new Double(s.getValor() );
            NumberFormat nf = NumberFormat.getCurrencyInstance();
            String formatado = nf.format(valor);
    //O resultado é R$ 12.000.000,12
    //Double.toString(s.getValor()).replace(".", ",")
    
            String dataFormatada = formato.format(s.getData());
            modelo.addRow(new Object[]{s.getNumero(), s.getClientes().getCpf(), s.getClientes().getNome(), s.getDescricao(),
                formatado, dataFormatada});
        }

        tbConsultaServicos.setModel(modelo);
    }

    /**
     * Creates new form ConsultaServico
     */
    public ConsultaServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtDataInicial = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDataFinal = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        txtGerarRelatorio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultaServicos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Consulta Serviços");

        jLabel2.setText("Data Incial:");

        try {
            txtDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Data Final:");

        try {
            txtDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        txtGerarRelatorio.setText("Gerar Relatório");
        txtGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGerarRelatorioActionPerformed(evt);
            }
        });

        tbConsultaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbConsultaServicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultar)
                        .addComponent(txtGerarRelatorio))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        try {
            this.listaServicos();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!" + ex.getMessage(), "Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGerarRelatorioActionPerformed
        try {
            Connection con = ConnectionFactory.conectar();

            HashMap parametros = new HashMap();

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date data_inicial = formato.parse(txtDataInicial.getText());
            Date data_final = formato.parse(txtDataFinal.getText());

            parametros.put("data_inicial", data_inicial);
            parametros.put("data_final", data_final);

            String caminho = "C:/relatorios/relatorio.jasper";
            //String caminho = "C:/Users/Elivelton Silva/Documents/NetBeansProjects/Rodrigo_Foto/src/relatorio_temp/relatorio.jasper";
            try {
                JasperPrint print = JasperFillManager.fillReport(caminho, parametros, con);

                JasperViewer jv = new JasperViewer(print, false);
                jv.setVisible(true); //chama o formulario para visualização
                jv.toFront(); //set o formulario a frente da aplicação
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao chamar o relatório!\nErro:" + ex);
                ex.printStackTrace();
            }

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!" + ex.getMessage(), "Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtGerarRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbConsultaServicos;
    private javax.swing.JFormattedTextField txtDataFinal;
    private javax.swing.JFormattedTextField txtDataInicial;
    private javax.swing.JButton txtGerarRelatorio;
    // End of variables declaration//GEN-END:variables
}
