package view;

import dao.ServicosDAO;
import factory.ConnectionFactory;
import java.sql.Connection;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Servicos;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class ConsultaNumeroServico extends javax.swing.JInternalFrame {

    Servicos servicos;
    ServicosDAO sdao;

    int numero = 0;

    /**
     * Creates new form ConsultaNumeroServico
     */
    public ConsultaNumeroServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumerSevico = new javax.swing.JTextField();
        btnConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicos = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setText("Número do Serviço:");

        btnConsulta.setText("Consultar");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        tblServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblServicosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblServicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumerSevico, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumerSevico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        try {
            DefaultTableModel modelo = new DefaultTableModel();

            modelo.addColumn("DATA");
            modelo.addColumn("NÚMERO");
            modelo.addColumn("VALOR");
            modelo.addColumn("CLIENTE");
            modelo.addColumn("DESCRIÇÃO");

            sdao = new ServicosDAO();

            for (Servicos s : sdao.buscarNumero(Integer.parseInt(txtNumerSevico.getText()))) {
                //formata data
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                String dataFormatada = formato.format(s.getData());

                //formata valor
                Double valor = new Double(s.getValor());
                NumberFormat nf = NumberFormat.getCurrencyInstance();
                String valor_formatado = nf.format(valor);

                modelo.addRow(new Object[]{dataFormatada, s.getNumero(), valor_formatado,
                    s.getClientes().getNome(), s.getDescricao()});

            }

            tblServicos.setModel(modelo);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Digite um valor válido!/Campo Obrigatório", "Atenção", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnConsultaActionPerformed

    private void tblServicosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServicosMousePressed
        

        Connection con = ConnectionFactory.conectar();

        HashMap parametros = new HashMap();

        parametros.put("numero", tblServicos.getModel().getValueAt(tblServicos.getSelectedRow(), 1));

        String caminho = "C:/relatorios/comprovante02.jasper";
        //String caminho = "C:/Users/Elivelton Silva/Documents/NetBeansProjects/Rodrigo_Foto/src/relatorio_temp/comprovante02.jasper";
        try {
            JasperPrint print = JasperFillManager.fillReport(caminho, parametros, con);

            JasperViewer jv = new JasperViewer(print, false);
            jv.setVisible(true); //chama o formulario para visualização
            jv.toFront(); //set o formulario a frente da aplicação
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao chamar o relatório!\nErro:" + ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tblServicosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblServicos;
    private javax.swing.JTextField txtNumerSevico;
    // End of variables declaration//GEN-END:variables
}
